name : Run job for examples folder
on: [workflow_dispatch]
jobs:
  examples-test:
    runs-on: ubuntu-latest
    container: openmodelica/openmodelica:v1.21.0-minimal
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          apt-get -qq update
          apt-get -qq --no-install-recommends install python3 python3-pip
          pip install numpy pandas
      - name: Install Modelica STL 4.0.0
        run: |
          echo "installPackage(Modelica, \"4.0.0+maint.om\", exactMatch=true);" > installModelicaStl.mos && omc installModelicaStl.mos
      - name: Install MoPyRegtest with current code
        run: |
          pip3 install --user .
      - name: Run regression test examples
        run: |
          cd examples
          python3 -m unittest
      - name: Run test generation examples with command line tool
        run: |
          cd examples/generate_tests
          mopyregtest ./gen_tests BlocksLpDist \
            ~/".openmodelica/libraries/Modelica 4.0.0+maint.om/" \
            Modelica.Blocks.Sources.Sine,Modelica.Blocks.Sources.ExpSine,Modelica.Blocks.Sources.Step \
            --metric=Lp_dist
      - name: Run test generation examples with script
        run: |
          cd examples/generate_tests
          python3 gentests_modelica_blocks_sources.py
          cd gen_tests
          python3 test_blockslpdist.py
          python3 test_blocksuserdef.py