name : Unit test job
on: [workflow_dispatch]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    container: openmodelica/openmodelica:v1.23.0-minimal
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install numpy pandas
      - name: Install Modelica STL 4.0.0
        run: |
          echo "installPackage(Modelica, \"4.0.0+maint.om\", exactMatch=true);" > installModelicaStl.mos && omc installModelicaStl.mos
      - name: Run unit tests
        run: |
          python -m pip install --user .
          cd tests
          python3 -m unittest
